Sprint 3
stvdent47/middle.messenger.praktikum.yandex pull request #7
Opened 2022-09-13 14:42 UTC by stvdent47

2022-09-13 19:48 UTC, ivan-infro commented on .gitignore
>  node_modules
Рекоммендую сюда добавить еще .DS_Store файлы, но перед этим закоммитить удаление данного файла (.DS_Store) из репозитория

2022-09-13 20:07 UTC, ivan-infro commented on src/api/auth/auth.ts
> +  signOut: () => HTTPTransport.post('/auth/logout', { ...options }),
В данном случае выполнять копирование объекта (делать { ...options }) необязательно

2022-09-13 20:09 UTC, ivan-infro commented on src/api/chat/chat.ts
> +      (JSON.parse(response) || []).map((dto: ChatViewDto) => new ChatView(dto)),
Из-за ошибки на сервере, или другой неполадки, в response может вернуться не валидный JSON (или любая другая строка). В таком случае вызов JSON.parse упадет с ошибкой в runtime. Места, в которых код взаимодействует с данными из вне, лучше дополнительно оборачивать в try...catch и обрабатывать возможные исключительные ситуации

2022-09-13 20:10 UTC, ivan-infro commented on src/api/user/user.ts
> +      // TODO — сделать отображение списка найденных пользователей при добавлении в чат
И обработать ситуацию, когда ни один пользователь не найден :)

2022-09-13 20:11 UTC, ivan-infro commented on src/components/Chat/ChatButton/ChatButton.ts
> +              {{ avatar }}
Проверяется chat.avatar, а выводится просто avatar. Ошибка?

2022-09-13 20:17 UTC, ivan-infro commented on src/index.ts
> +  // setTimeout(() => {
Не храните закомментированный и неиспользуемый код в репозитории. Это снижает читаемость кода

2022-09-13 20:20 UTC, ivan-infro requested changes

2022-09-13 20:20 UTC, ivan-infro commented on src/core/BrowseRouter.ts
> +      this.#block.hide();
Необходимо полностью удалять страницу из DOM

>В DOM может быть активна только одна страница (при переходе на новую страницу, не забудьте проверить, что старая была удалена из него).

2022-09-14 17:40 UTC, stvdent47 commented on src/api/auth/auth.ts
> +  signOut: () => HTTPTransport.post('/auth/logout', { ...options }),
withCredentials необходим, его оставил, остальное убрал

2022-09-14 17:41 UTC, stvdent47 commented on src/api/chat/chat.ts
> +      (JSON.parse(response) || []).map((dto: ChatViewDto) => new ChatView(dto)),
изменил метод, правильно ли я понял? (если правильно другие потом тоже перепишу)

2022-09-14 17:43 UTC, stvdent47 commented on src/core/BrowseRouter.ts
> +      this.#block.hide();
не совсем понимаю логику: в теории практикума и на вебинарах показывали именно такой способ (скрытие и отображение), поэтому его и выбрал (потратил много времени, честно говоря, были проблемы, а способ через замену работал), но поправить не долго, сделал

2022-09-14 20:40 UTC, ivan-infro commented on src/api/chat/chat.ts
> +      (JSON.parse(response) || []).map((dto: ChatViewDto) => new ChatView(dto)),
Да, так лучше 👍

2022-09-14 20:59 UTC, ivan-infro commented on src/core/BrowseRouter.ts
> +      this.#block.hide();
Скрытые через `display: none` элементы присутствуют в DOM дереве и замедляют поиск элементов по нему, браузер тратит ресурсы на разбор элементов, которые пользователь, возможно, никогда не увидит. То, как реализовано теперь (с заменой контента в `#root`) больше похоже на то, как работают популярные роутеры.
В методе hide можно генерировать событие, которое подскажет Блоку, что он будет размонтирован.

2022-09-22 10:19 UTC, merged